# Generated by Django 4.1.7 on 2023-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lip_premium', models.IntegerField(blank=True, null=True)),
                ('lip_value', models.IntegerField(blank=True, null=True)),
                ('pf_selfcont', models.IntegerField(blank=True, null=True)),
                ('pf_company_con', models.IntegerField(blank=True, null=True)),
                ('saf', models.IntegerField(blank=True, null=True)),
                ('benevolent_fund', models.IntegerField(blank=True, null=True)),
                ('group_insurance_pre', models.IntegerField(blank=True, null=True)),
                ('dps', models.IntegerField(blank=True, null=True)),
                ('investment_saving_cert', models.IntegerField(blank=True, null=True)),
                ('investment_icb', models.IntegerField(blank=True, null=True)),
                ('investment_gob_BandC', models.IntegerField(blank=True, null=True)),
                ('donation_gov_approve', models.IntegerField(blank=True, null=True)),
                ('investment_share_deb', models.IntegerField(blank=True, null=True)),
                ('investment_bond', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
