# Generated by Django 4.1.7 on 2023-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoHouseProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_income', models.IntegerField(blank=True, null=True)),
                ('allowable_rp', models.IntegerField(blank=True, null=True)),
                ('tax_municipal', models.IntegerField(blank=True, null=True)),
                ('land_revenue', models.IntegerField(blank=True, null=True)),
                ('interest_loan', models.IntegerField(blank=True, null=True)),
                ('insurance_premium', models.IntegerField(blank=True, null=True)),
                ('vacancy_allowance', models.IntegerField(blank=True, null=True)),
                ('interest_mortgage', models.IntegerField(blank=True, null=True)),
                ('capital_charge', models.IntegerField(blank=True, null=True)),
                ('other_exp', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
