# Generated by Django 4.1.7 on 2023-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationAssessee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=64)),
                ('name_assessee', models.CharField(blank=True, max_length=64)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('financial_year', models.CharField(blank=True, choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031'), ('2031-2032', '2031-2032'), ('2032-2033', '2032-2033')], max_length=32)),
                ('assessment_year', models.CharField(blank=True, choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031'), ('2031-2032', '2031-2032'), ('2032-2033', '2032-2033')], max_length=32)),
                ('employer', models.CharField(blank=True, max_length=64)),
                ('father_name', models.CharField(blank=True, max_length=64)),
                ('mother_name', models.CharField(blank=True, max_length=64)),
                ('spouse_name', models.CharField(blank=True, max_length=64)),
                ('nid', models.CharField(blank=True, max_length=64)),
                ('tin', models.CharField(blank=True, max_length=64)),
                ('circle_tax', models.CharField(blank=True, max_length=64)),
                ('zone_tax', models.CharField(blank=True, max_length=64)),
                ('email_personal', models.EmailField(blank=True, max_length=64, unique=True)),
                ('email_official', models.EmailField(blank=True, max_length=64, unique=True)),
                ('mobile_personal', models.CharField(blank=True, max_length=32)),
                ('mobile_official', models.CharField(blank=True, max_length=32)),
                ('address_present', models.CharField(blank=True, max_length=256)),
                ('address_permanent', models.CharField(blank=True, max_length=256)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('place', models.CharField(blank=True, max_length=32)),
                ('group_name', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
