# Generated by Django 4.1.7 on 2023-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAgricalture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_from_sales', models.IntegerField(blank=True, null=True)),
                ('income_from_borga', models.IntegerField(blank=True, null=True)),
                ('income_from_processing', models.IntegerField(blank=True, null=True)),
                ('income_from_caltivation', models.IntegerField(blank=True, null=True)),
                ('total_agri_income', models.IntegerField(blank=True, null=True)),
                ('allowabe_exp', models.IntegerField(blank=True, null=True)),
                ('land_tax', models.IntegerField(blank=True, null=True)),
                ('interest_against_capital', models.IntegerField(blank=True, null=True)),
                ('other_exp_agri', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
