# Generated by Django 4.1.7 on 2023-03-29 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information_assessee', '0001_initial'),
        ('information_salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxableSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.IntegerField(blank=True, null=True)),
                ('special_pay', models.IntegerField(blank=True, null=True)),
                ('dearness_allowance', models.IntegerField(blank=True, null=True)),
                ('servant_allowance', models.IntegerField(blank=True, null=True)),
                ('leave_allowance', models.IntegerField(blank=True, null=True)),
                ('honorarium_reward_fees', models.IntegerField(blank=True, null=True)),
                ('overtime_allowance', models.IntegerField(blank=True, null=True)),
                ('bonus_Ex_gratia', models.IntegerField(blank=True, null=True)),
                ('pf_employer', models.IntegerField(blank=True, null=True)),
                ('deemed_income_tran', models.BooleanField(default=True)),
                ('deemed_income_accr', models.BooleanField(default=True)),
                ('fastival_bonus', models.IntegerField(blank=True, null=True)),
                ('accinterest_pf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accinterest_pfs', to='information_salary.informationsalary')),
                ('conveyance_allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conveyance_allowances', to='information_salary.informationsalary')),
                ('houserent_allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houserent_allowances', to='information_salary.informationsalary')),
                ('medical_allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_allowances', to='information_salary.informationsalary')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_assessee.informationassessee')),
                ('wwf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wwfs', to='information_salary.informationsalary')),
            ],
        ),
    ]
